spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss   
  cloud:
    sentinel:
      enabled: true
      transport:
        # sentinel dashboard 地址
        dashboard: localhost:8180

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        loggerLevel: FULL
  httpclient:
    enabled: true


ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000    